### ISSUE TITLE
Custom Background Color Not Working 

### ISSUE THREAD

**Issue by acopetkovic** [MaxAst/expo-share-extension#35] opened 2024-06-11 14:16 UTC
I can't get the custom background color set. Testing on iOS simulator with iOS 17. Also other custom settings are not working for me. Am I missing something? 

`
 "plugins": [
      [
        "expo-share-extension",
        {
          "backgroundColor": {
            "red": 255,
            "green": 255,
            "blue": 255,
            "alpha": 0
          }
        }
      ]
    ]
`

**Comment by acopetkovic** [comment] 2024-06-11 16:29
I want the transparent background, that is the issue

**Comment by MaxAst** [comment] 2024-06-11 17:07
I'd need more context to help you debug this, could you pls create a repro? Also, have you tried running the basic example in this repo? It uses a custom background and it's working there

**Comment by acopetkovic** [comment] 2024-06-12 15:45
So basically I followed installation guide until this point:

- Need a way to close the share extension? Use the close method from expo-share-extension

I created ShareExtension.js and it's working fine, I can see my app in share options and ulr is being shared as it should. But when I try to edit my app.js to have transparent background of share extension screen, it fails to do so.

**Comment by MaxAst** [comment] 2024-06-12 16:26
did you re-run prebuild after doing the change?

**Comment by dtorras** [comment] 2024-06-13 15:56
@MaxAst I'm not able to reproduce the issue right now but that also happened to me. Rebuilding was not updating the native file (plist I think) with the background color property. When I manually updated that file matching the JS config, it worked correctly.

**Comment by MaxAst** [comment] 2024-06-14 09:04
did you add the `--clean` flag to your prebuild command, like so `expo prebuild --clean`? I think if you don't add it, it could be that prebuild doesn't update Info.plist.

**Comment by acopetkovic** [comment] 2024-06-14 09:15
@MaxAst expo prebuild --clean was the solution

**Comment by MaxAst** [comment] 2024-06-14 13:52
perfect, will close the issue, let me know if you run into any other issues

**Closed by MaxAst** 2024-06-14 13:52 UTC

**Comment by anastely** [comment] 2024-09-05 09:23
Hey @MaxAst
Is there any way to customise UI not just the background?
I want to get some data from zustand store and render it in the view along side with the shared URL

Something like this
<img width="215" alt="Screenshot 2024-09-05 at 12 19 39 PM" src="https://github.com/user-attachments/assets/b92df642-9d17-4666-80d6-14a00a9cb822"> <img width="385" alt="Screenshot 2024-09-05 at 12 21 49 PM" src="https://github.com/user-attachments/assets/3498521c-c065-48c4-bc3e-33dc21b00e13">
